src/CuentaPorCobrar/CuentaPorCobrar/ViewModels/TipoDocumentoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CuentaPorCobrar.ViewModels
{
    public class TipoDocumentoViewModel
    {
        public int TipoDocumentoId { get; set; }

        [Display(Name = "Descripción")]
        [StringLength(50)]
        [Required(ErrorMessage = "El Campo Descripción debe tener una longitud máxima de 50")]
        [RegularExpression(@"\w{40}", ErrorMessage = "Esta descripción es demasiada larga")]
        public string Descripcion { get; set; }

        [Display(Name = "Cuenta")]
        public int CuentaId { get; set; }

        public virtual CuentaViewModel Cuenta { get; set; }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Controllers/TipoDocumentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CuentaPorCobrar.DataAccess.Modelos;
using CuentaPorCobrar.DataAccess.Contexto;
using CuentaPorCobrar.ViewModels;
using AutoMapper;

namespace CuentaPorCobrar.Controllers
{
    [Authorize]
    public class TipoDocumentoController : BaseController
    {
        // GET: /TipoDocumento/
        public ActionResult Index(string criterio)
        {
            List<TipoDocumentoViewModel> tipoDocVms = new List<TipoDocumentoViewModel>();
            var tipoDocumentos = Contexto.TiposDocumento.Where(c =>
                (string.IsNullOrEmpty(criterio) ||
                c.Descripcion.ToLower().Contains(criterio.ToLower())
                ) && c.Estado).ToList();

            foreach (TipoDocumento tipoDocumento in tipoDocumentos)
            {
                var tipoDocVm = new TipoDocumentoViewModel();
                Mapper.DynamicMap(tipoDocumento, tipoDocVm);
                tipoDocVms.Add(tipoDocVm);
            }

            return View(tipoDocVms);
        }

        // GET: /TipoDocumento/Create
        public ActionResult Crear()
        {
            ViewBag.ListaCuentas = ObtenerCuentas();
            return View();
        }

        // POST: /TipoDocumento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(TipoDocumentoViewModel tipodocumento)
        {
            try
            {
                TipoDocumento tipoDocumentoNuevo = new TipoDocumento();
                Mapper.DynamicMap(tipodocumento, tipoDocumentoNuevo);
                Contexto.TiposDocumento.Add(tipoDocumentoNuevo);
                Contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }

        }

        // GET: /TipoDocumento/Edit/5
        public ActionResult Editar(int? id)
        {
            TipoDocumentoViewModel tipoDocVm = new TipoDocumentoViewModel();
            var tipoDocumento = Contexto.TiposDocumento
                .SingleOrDefault(c => c.TipoDocumentoId == id);
            ViewBag.ListaCuentas = ObtenerCuentas();
            Mapper.DynamicMap(tipoDocumento, tipoDocVm);
            return View(tipoDocVm);
        }

        // POST: /TipoDocumento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(TipoDocumentoViewModel tipodocumento)
        {
            try
            {
                TipoDocumento tipoDocumentoNuevo = new TipoDocumento();
                Mapper.DynamicMap(tipodocumento, tipoDocumentoNuevo);
                Contexto.Entry(tipoDocumentoNuevo).State = EntityState.Modified;
                Contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View();
            }
        }

        // GET: /TipoDocumento/Delete/5
        public ActionResult Eliminar(int id)
        {
            TipoDocumento tipodocumento = Contexto.TiposDocumento.Find(id);
            tipodocumento.Estado = false;
            Contexto.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/TipoDocumento/Crear.cshtml
@model CuentaPorCobrar.ViewModels.TipoDocumentoViewModel

<h2>Crear</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descripcion)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuentaId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CuentaId, (IEnumerable<SelectListItem>)ViewBag.ListaCuentas, new { @class = "chzn-select" })
                @Html.ValidationMessageFor(model => model.CuentaId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Styles{
    <link href="@Url.Content("~/Content/bootstrap-chosen.css")" rel="stylesheet" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/chosen.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/Custom/ChosenConfig.js")"></script>
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/TipoDocumento/Editar.cshtml
@model CuentaPorCobrar.ViewModels.TipoDocumentoViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TipoDocumento</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.TipoDocumentoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descripcion)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuentaId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CuentaId, (IEnumerable<SelectListItem>)ViewBag.ListaCuentas, new { @class = "chzn-select" })
                @Html.ValidationMessageFor(model => model.CuentaId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Styles{
    <link href="@Url.Content("~/Content/bootstrap-chosen.css")" rel="stylesheet" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/chosen.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/Custom/ChosenConfig.js")"></script>
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/TipoDocumento/Index.cshtml
@model IEnumerable<CuentaPorCobrar.ViewModels.TipoDocumentoViewModel>

<h2>Tipos de Documentos</h2>

<div class="row">
    <div class="col-lg-6 col-md-6">
        <form class="form-inline" action="@Url.Action("Index","TipoDocumento")" method="get">
            <div class="form-group">
                <input class="form-control" type="text" name="criterio" />
            </div>
            <input class="btn btn-default" type="submit" name="name" value="Buscar" />
        </form>
    </div>
    <div class="col-lg-6 col-md-6">
        <a class="btn btn-default pull-right" href="@Url.Action("Crear", "TipoDocumento")">Agregar</a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12 col-md-12">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(c=>c.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.Cuenta.Nombre)
                </th>
                <th>Acciones</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cuenta.Nombre)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", new { id = item.TipoDocumentoId }) |
                        @Html.ActionLink("Eliminar", "Eliminar", new { id = item.TipoDocumentoId })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>