src/CuentaPorCobrar/CuentaPorCobrar/ViewModels/TransaccionViewModel.cs
using CuentaPorCobrar.DataAccess.Modelos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;

namespace CuentaPorCobrar.ViewModels
{
    public class TransaccionViewModel
    {
        public int TransaccionId { get; set; }

        [Display(Name = "Tipo de Documento")]
        [Required]
        public int TipoDocumentoId { get; set; }

        [Display(Name = "Cliente")]
        [Required]
        public int ClienteId { get; set; }

        [Display(Name = "Tipo de Movimiento")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public TipoMovimiento TipoMovimiento { get; set; }

        [Display(Name = "Número de Documento")]
        public Guid NumeroDocumento { get; set; }

        public SqlDateTime Fecha { get; set; }

        [Range(0, double.MaxValue)]
        [Required(ErrorMessage = "Este campo es requerido")]
        public decimal Monto { get; set; }

        public virtual ClienteViewModel Cliente { get; set; }
        public virtual TipoDocumentoViewModel TipoDocumento { get; set; }

        public TransaccionViewModel()
        {
            Fecha = DateTime.Now;
            NumeroDocumento = Guid.NewGuid();
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Controllers/TransaccionController.cs
using AutoMapper;
using CuentaPorCobrar.DataAccess.Modelos;
using CuentaPorCobrar.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CuentaPorCobrar.Controllers
{
    [Authorize]
    public class TransaccionController : BaseController
    {
        //
        // GET: /Transaccion/
        public async Task<ActionResult> Index(string criterio)
        {
            return await Task.Run(() =>
            {
                List<TransaccionViewModel> transaccionVms = new List<TransaccionViewModel>();
                var resultado = Contexto.Transacciones.Where(c =>
                    (string.IsNullOrEmpty(criterio) || c.Cliente.Nombre.Contains(criterio)) ||
                    (string.IsNullOrEmpty(criterio) || c.TipoDocumento.Descripcion.Contains(criterio))
                ).ToList();

                foreach (Transaccion transaccion in resultado)
                {
                    var transaccionVm = new TransaccionViewModel();
                    Mapper.DynamicMap(transaccion, transaccionVm);
                    transaccionVms.Add(transaccionVm);
                }

                return View(transaccionVms);
            });
        }

        //
        // GET: /Transaccion/Create
        public ActionResult Crear()
        {
            ViewBag.TiposDocumento = ObtenerTipoDocumento();
            ViewBag.Clientes = ObtenterClientes();
            return View();
        }

        //
        // POST: /Transaccion/Create
        [HttpPost]
        public ActionResult Crear(TransaccionViewModel transaccion)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Transaccion transaccionNueva = new Transaccion();
                    //AfectarBalance(transaccion.ClienteId, transaccion.Monto, transaccion.TipoMovimiento);
                    Mapper.DynamicMap(transaccion, transaccionNueva);
                    Contexto.Transacciones.Add(transaccionNueva);
                    Contexto.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Crear");
            }
            catch
            {
                return RedirectToAction("Crear");
            }
        }

        private void AfectarBalance(int clienteId, decimal transaccionMonto, TipoMovimiento tipoMovimiento)
        {
            var balance = Contexto.Balances.Single(c => c.ClienteId == clienteId);

            switch (tipoMovimiento)
            {
                case TipoMovimiento.Credito:
                    balance.Monto -= transaccionMonto;
                    break;
                case TipoMovimiento.Debito:
                    balance.Monto += transaccionMonto;
                    break;
                default:
                    break;
            }

            Contexto.SaveChanges();
        }

    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/Transaccion/Crear.cshtml
@using CuentaPorCobrar.DataAccess.Modelos
@model CuentaPorCobrar.ViewModels.TransaccionViewModel
@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaccion</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.TipoDocumentoId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.TipoDocumentoId, (IEnumerable<SelectListItem>)ViewBag.TiposDocumento, new { @class = "form-control chzn-select" })
                @Html.ValidationMessageFor(model => model.TipoDocumentoId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.ClienteId, (IEnumerable<SelectListItem>)ViewBag.Clientes, new { @class = "form-control chzn-select" })
                @Html.ValidationMessageFor(model => model.ClienteId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <div>
                    @Html.LabelFor(model => model.TipoMovimiento, new { @class = "control-label col-md-2" })
                </div>
                <label>
                    Cr&eacute;dito
                    @Html.RadioButtonFor(model => model.TipoMovimiento, TipoMovimiento.Credito)
                </label>

                <label>
                    D&eacute;bito
                    @Html.RadioButtonFor(model => model.TipoMovimiento, TipoMovimiento.Debito)
                </label>

                @Html.ValidationMessageFor(model => model.TipoMovimiento)
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.NumeroDocumento, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.NumeroDocumento, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NumeroDocumento)
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Monto, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Monto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>


@section Styles{

    <link href="@Url.Content("~/Content/bootstrap-chosen.css")" rel="stylesheet" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/chosen.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/Custom/ChosenConfig.js")"></script>
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/Transaccion/Index.cshtml
@model IEnumerable<CuentaPorCobrar.ViewModels.TransaccionViewModel>

<h2>Transacciones</h2>

<div class="row">
    <div class="col-lg-6 col-md-6">
        <form class="form-inline" action="@Url.Action("Index", "Transaccion")" method="get">
            <div class="form-group">
                <input class="form-control" type="text" name="criterio" />
            </div>
            <input class="btn btn-default" type="submit" name="name" value="Buscar" />
        </form>
    </div>
    <div class="col-lg-6 col-md-6">
        <a class="btn btn-default pull-right" href="@Url.Action("Crear", "Transaccion")">Agregar</a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(c => c.Cliente.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.TipoDocumento.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.TipoMovimiento)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.NumeroDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.Fecha)
                </th>
                <th>
                    @Html.DisplayNameFor(c => c.Monto)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cliente.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoDocumento.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoMovimiento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroDocumento)
                    </td>
                    <td>
                        @item.Fecha.ToString()
                    </td>
                    <td>
                        @string.Format("{0:C}", item.Monto)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>