src/CuentaPorCobrar/CuentaPorCobrar/Controllers/BalanceController.cs
using AutoMapper;
using CuentaPorCobrar.DataAccess.Modelos;
using CuentaPorCobrar.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CuentaPorCobrar.Controllers
{
    [Authorize]
    public class BalanceController : BaseController
    {
        //
        // GET: /Balance/
        public async Task<ActionResult> Index(string criterio)
        {
            return await Task.Run(() =>
            {
                List<BalanceViewModel> vms = new List<BalanceViewModel>();
                var balances = Contexto.Balances.ToList().Where(c =>
                    (string.IsNullOrEmpty(criterio) || c.Cliente.Nombre.Contains(criterio)) ||
                    (string.IsNullOrEmpty(criterio) || c.Corte.ToString("dd-MM-yyyy").Contains(criterio)) ||
                    (string.IsNullOrEmpty(criterio) || c.Monto.ToString().Contains(criterio))).ToList();

                foreach (var balance in balances)
                {
                    var vm = new BalanceViewModel();
                    Mapper.DynamicMap(balance, vm);
                    vms.Add(vm);
                }

                return View(vms);
            });
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Controllers/ClienteController.cs
using AutoMapper;
using CuentaPorCobrar.DataAccess.Modelos;
using CuentaPorCobrar.Util;
using CuentaPorCobrar.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CuentaPorCobrar.Controllers
{
    [Authorize]
    public class ClienteController : BaseController
    {
        //
        // GET: /Cliente/
        public async Task<ActionResult> Index(string criterio)
        {
            return await Task.Run(() =>
            {
                var clienteVMS = new List<ClienteViewModel>();
                var clientes = Contexto.Clientes.Where(c =>
                    (string.IsNullOrEmpty(criterio) ||
                    (c.Nombre + c.Cedula).ToLower().Contains(criterio.ToLower()))).ToList();

                foreach (var elemento in clientes)
                {
                    var vm = new ClienteViewModel();
                    Mapper.DynamicMap(elemento, vm);
                    clienteVMS.Add(vm);
                }

                return View(clienteVMS);
            });
        }

        //
        // GET: /Cliente/Create
        public ActionResult Crear()
        {
            return View();
        }

        //
        // POST: /Cliente/Create
        [HttpPost]
        public ActionResult Crear(ClienteViewModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!Helper.ValidarCedula(cliente.Cedula))
                    {
                        ModelState.AddModelError("Cedula", "Cedula no válida");
                        return View(cliente);
                    }
                    Cliente nuevoCliente = new Cliente();

                    cliente.Cedula = cliente.Cedula.Replace("-", "").Trim();
                    Mapper.DynamicMap(cliente, nuevoCliente);

                    CrearBalancePara(nuevoCliente);

                    Contexto.Clientes.Add(nuevoCliente);

                    Contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (DbUpdateException dbuex)
            {
                ModelState.AddModelError("Cedula", "Ya existe un cliente con esta cédula");
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        //
        // GET: /Cliente/Edit/5
        public ActionResult Editar(int id)
        {
            var clienteExistente = Contexto.Clientes
                    .SingleOrDefault(c => c.ClienteId == id);
            var vm = new ClienteViewModel();
            Mapper.DynamicMap(clienteExistente, vm);
            return View(vm);
        }

        //
        // POST: /Cliente/Edit/5
        [HttpPost]
        public ActionResult Editar(ClienteViewModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!Helper.ValidarCedula(cliente.Cedula))
                    {
                        ModelState.AddModelError("Cedula", "Cedula no válida");
                        return View(cliente);
                    }
                }
                Cliente clienteModificado = new Cliente();
                Mapper.DynamicMap(cliente, clienteModificado);
                Contexto.Entry(clienteModificado).State = EntityState.Modified;
                Contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Cliente/Delete/5
        public ActionResult Eliminar(int id)
        {
            try
            {
                var clientes = Contexto.Clientes
                    .SingleOrDefault(c => c.ClienteId == id);
                Contexto.Clientes.Remove(clientes);
                Contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void CrearBalancePara(Cliente nuevoCliente)
        {
            Contexto.Balances.Add(new Balance()
            {
                ClienteId = nuevoCliente.ClienteId,
                Corte = DateTime.Today,
                Monto = 0
            });
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Controllers/CuentaController.cs
using AutoMapper;
using CuentaPorCobrar.DataAccess.Modelos;
using CuentaPorCobrar.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuentaPorCobrar.Controllers
{
    [Authorize]
    public class CuentaController : BaseController
    {
        // GET: Cuenta
        public ActionResult Index()
        {
            return View(Contexto.Cuentas.ToList());
        }

        // GET: Cuenta/Create
        public ActionResult Crear()
        {
            return View();
        }

        // POST: Cuenta/Create
        [HttpPost]
        public ActionResult Crear(CuentaViewModel cuenta)
        {
            try
            {
                Cuenta cuentaNueva = new Cuenta();
                Mapper.DynamicMap(cuenta, cuentaNueva);
                Contexto.Cuentas.Add(cuentaNueva);
                Contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cuenta/Edit/5
        public ActionResult Editar(int id)
        {
            return View(Contexto.Cuentas.Find(id));
        }

        // POST: Cuenta/Edit/5
        [HttpPost]
        public ActionResult Editar(CuentaViewModel cuenta)
        {
            try
            {
                Cuenta cuentaModificada = new Cuenta();
                Mapper.DynamicMap(cuenta, cuentaModificada);
                Contexto.Entry(cuentaModificada).State = EntityState.Modified;
                Contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cuenta/Delete/5
        public ActionResult Eliminar(int id)
        {
            try
            {
                var cuenta = Contexto.Cuentas.Find(id);
                Contexto.Cuentas.Remove(cuenta);
                Contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuentaPorCobrar.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ReporteController : BaseController
    {
        // GET: Reporte
        public ActionResult Generar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Generar(int antiguedadSaldo = 0)
        {
            Session["antiguedadSaldo"] = antiguedadSaldo;
            return Redirect("~/Reporte/Reporte.aspx");
        }
    }
}

src/CuentaPorCobrar/CuentaPorCobrar/Views/Shared/_Layout.cshtml
@using System.Web.Configuration

@{
    var nombreAplicacion = WebConfigurationManager.AppSettings["NombreAplicacion"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.NombreAplicacion</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/jquery-ui")
    @RenderSection("Styles", false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(nombreAplicacion, "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle"
                            data-toggle="dropdown"
                            role="button"
                            aria-haspopup="true"
                            aria-expanded="false">Administrar <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index","Cliente")">Clientes</a></li>
                            <li><a href="@Url.Action("Index","Balance")">Balances</a></li>
                            <li><a href="@Url.Action("Index","TipoDocumento")">Tipos de Documento</a></li>
                            <li><a href="@Url.Action("Index","Transaccion")">Transacciones</a></li>
                            <li><a href="@Url.Action("Index","Cuenta")">Cuentas</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Generar","Reporte")">Generar Reporte</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Today.Year - @nombreAplicacion</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>